# Generated by Django 5.1.2 on 2024-10-16 09:55

from django.db import migrations


def split_name(apps, schema_editor):
    student_model = apps.get_model('students', 'Student')

    for student in student_model.objects.all():
        if ' ' in student.name:
            first_name, last_name = student.name.split(' ', 1)
            student.first_name = first_name
            student.last_name = last_name
        else:
            student.first_name = student.name
            student.last_name = ''
        student.save()



class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RunPython(split_name)
    ]
